name: "CI"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: 'cybertreiber'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix --version
    - run: nix flake check -L --keep-going
    - run: nix flake show
    - run: nix develop -c which repl
    - run: nix develop .#packages -c echo built
