name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '4 0 * * 2,5'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/update-flake-lock@v23
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-assignees: ahirner
